### PR TITLE
reorder job cleanup and completion time setting

### PR DESCRIPTION
**Pull request by shaowei-su**
Follow to tf-operator issue: https://github.com/kubeflow/tf-operator/issues/1223
Reorder the `jobStatus.CompletionTime` before job cleanup, where completion time is used for TTL check.

### CODE REVIEW

**Comment by shaowei-su** [comment]
@googlebot I signed it!

**Review by terrytangyuan — APPROVED** [review]
Good catch!

/lgtm
/approve

**Comment by shaowei-su** [comment]
@googlebot I fixed it.

**Comment by shaowei-su** [comment]
@terrytangyuan  thanks for the stamp! it seems that master branch CI build is failing:
```
./hack/../pkg is out of date. Please run hack/update-codegen.sh
The command "./hack/verify-codegen.sh" exited with 1.
```
any suggestions on how to fix this?

**Comment by terrytangyuan** [comment]
Could you run `hack/update-codegen.sh` to see if there's any update in codegen that needs to be updated?

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Comment by shaowei-su** [comment]
Hi @terrytangyuan  is it possible to cut a new release for common, so that downstream issue can be resolved: https://github.com/kubeflow/tf-operator/issues/1223

**Pull request merged**
