### PR TITLE
Enhance maintainability of operator common module

### PR DESCRIPTION
**Pull request by Jeffwan**
Address issue #54 

- Upgrade go mod to use kubernetes 1.15.10 - it should be compatible with latest operator framework. (kubebuilder or operator-sdk)
  - 1.15.x is the first version supports go modules
  - As Kubernetes is directly imported, we need replace all sub modules

- Reorganize the code structure 
  - separate test_job and core common apis & libraries. The may reason is we don't want to mix core api and test_job (used for testing). separate test_job directory helps user understand how to write a custom operator. 
  - bring version concept for extension in the future

- Update CI scripts
 - Upgrade golang to 1.13
 - Add ./hack/verify-codegen.sh step in CI scripts to verify API changes

- Update hack scripts
  - Fix `update-codegen` and make it work with current structure
  - Read CODEGEN_PKG and OPENAPI_PKG from go mod and deprecate local vendor/
  - Update right path for clientset and API deepcopy
  - Add ${TMP_DIR} support and make sure scripts work for package outside $GOPATH

- Clean up go module
  - all modules verified now

Current code structure is like below. It make sure once we can grow the project smoothly if we have v2alpha1 v2beta1. 

```
.
├── LICENSE
├── OWNERS
├── README.md
├── go.mod
├── go.sum
├── hack
│   ├── boilerplate
│   ├── scripts
│   ├── update-codegen.sh
│   └── verify-codegen.sh
├── pkg
│   ├── apis
│   │   └── common
│   │       └── v1
│   ├── controller.v1
│   │   └── common
│   │       ├── job.go
│   │       ├── job_controller.go
│   │       ├── ......
│   │       ├── status_test.go
│   │       ├── util.go
│   │       └── util_test.go
├── test_job
│   ├── README.md
│   ├── apis
│   │   └── test_job
│   │       └── v1
│   ├── client
│   │   ├── clientset
│   │   ├── informers
│   │   └── listers
│   ├── controller.v1
│   │   └── test_job
│   │       └── test_job_controller.go
│   └── test_util
│       └── v1
│           ├── const.go
│           ├── ...
│           └── util.go
└── vendor
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/common/55)

### CODE REVIEW

**Comment by Jeffwan** [comment]
New commit is to fix linter issues. Bring a new linter_config and upgrade golinter-ci version.

**Comment by gaocegege** [comment]
Thanks for the PR. LGTM

/assign @johnugeorge @ChanYiLin @richardsliu @merlintang

**Comment by Jeffwan** [comment]
@gaocegege User doesn't need to change and it won't break the build.  Unless user want to use latest version. `go mod tidy` will try to update to latest version of the repo.

I can help update xgoost-operator. Actually, we should migrate other operators to use this as well. Most of the operators are using common API and job controller implementation of tf-operator. Dependency of tf-operator should be removed from other operators and migrate to common. I can help on that once we finish common module improvement. 

https://github.com/kubeflow/pytorch-operator/blob/047cf0f41e68e030158f532017a226c18827a660/pkg/controller.v1/pytorch/controller.go#L44-L46

https://github.com/kubeflow/mxnet-operator/blob/ee268609822733c3f859b54e8096d87045245be9/pkg/controller.v1/mxnet/controller.go#L42-L43

**Comment by terrytangyuan** [comment]
@Jeffwan That would be great. Thank you!

**Comment by gaocegege** [comment]
@Jeffwan Awesome! Thanks. I think tf-operator should use this common package, too.

/cc @johnugeorge

**Comment by merlintang** [comment]
great work！

**Comment by ChanYiLin** [comment]
@Jeffwan this is great
I will see if there is anything I can help

**Comment by johnugeorge** [comment]
Looks good. There are some fixes which have gone in tf operator job controller implementation. This have to be ported to common package.

**Pull request merged**
