### PR TITLE
Adding compatibility for API supporting HPA

### PR DESCRIPTION
**Pull request by johnugeorge**
`LabelSelector` field is restored to provide compatibility with the current API.  Instead, `Selector` field will be used for HPA feature 

Related: #197 https://github.com/kubeflow/training-operator/issues/1725

### CODE REVIEW

**Comment by johnugeorge** [comment]
@tenzen-y Once this is merged, we can create a new release in kubeflow/common 
Ref: https://github.com/kubeflow/training-operator/pull/1724/files#r1080943248

**Review by tenzen-y — COMMENTED** [review]
Thanks!
/lgtm

/assign @terrytangyuan @gaocegege

**Comment by tenzen-y** [comment]
@johnugeorge Can you rerun `hack/update-codegen.sh`?

```shell
@@ -231,7 +231,7 @@ func schema_pkg_apis_common_v1_ReplicaSt
 					},
 					"selector": {
 						SchemaProps: spec.SchemaProps{
-							Description: "A Selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty Selector matches all objects. A null Selector matches no objects.",
+							Description: "A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.",
 							Type:        []string{"string"},
 							Format:      "",
 						},
./hack/../pkg is out of date. Please run hack/update-codegen.sh
```

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
