### PR TITLE
Remove deprecated labels

### LINKED ISSUE #149: Fully-qualified labels migration tasks
These tasks must be completed to finalize the migration to fully qualified labels #148 

- [x] Migrate `SyncPdb` to non-deprecated label
- [x] Remove deprecated selector from `FilterPodsForReplicaType`
- [x] Remove deprecated selector from `FilterServicesForReplicaType`
- [x] Remove deprecated labels from API
- [x] Remove deprecated labels usage from pkg/util/labels
- [x] Remove deprecated labels from `GenLabels`

### PR DESCRIPTION
**Pull request by johnugeorge**
Remove deprecated labels from pods and services 

Fixes: https://github.com/kubeflow/common/issues/149

Changes in Training operator will be created once this is merged

### CODE REVIEW

**Comment by johnugeorge** [comment]
/assign @alculquicondor 

/cc @kubeflow/wg-training-leads 

/hold
Hold till review is completed

**Comment by alculquicondor** [comment]
/lgtm

Just make sure this change is restricted to a minor version upgrade (at least) and that it's properly documented.

**Comment by johnugeorge** [comment]
Yes. We will create a new release after this merge so that operators can use this. We will add a note in KF release that deprecated labels are removed in the release.

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by johnugeorge** [comment]
Thanks

/hold cancel

**Pull request merged**
