### PR TITLE
Make UpdateJobConditions public to be used by custom operators

### PR DESCRIPTION
**Pull request by jian-he**
UpdateJobConditions can be used as the util method by custom operators when updating the JobStatus in the UpdateJobStatus api

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/common/30)

### CODE REVIEW

**Comment by jian-he** [comment]
sounds good, which package/file should we put ? 
util/util.go ?

**Comment by gaocegege** [comment]
SGTM. job_controller/util.go

**Comment by jian-he** [comment]
I ended up moving the util methods to util/status.go.  Please check if making sense

**Comment by jian-he** [comment]
this patch only moves the code from one to another and should not affect test coverage

**Pull request merged**
