### PR TITLE
Create expectation package

### LINKED ISSUE #48: Delete direct dependency of kubernetes
Now go.mod has dependency of kubernetes v1.11.2.
It will be hard to import job_controller/pkg/api because of compatibility with new version client-go

### PR DESCRIPTION
**Pull request by Jeffwan**
Resolve #48.  Besides #73, this is the last PR to remove direct Kubernetes dependency. I think current strategy is folk PodControlInterface and Expectations from main Kubernetes pkg and maintain in common repo. This also helps to make sure our code is reliable without worrying about changes K8s version upgrade brings.

For long term, I will try to brings these changes to `kubernetes/client-go` and we can use client-go directly. Track progress here. https://github.com/kubernetes/client-go/issues/332

The purpose of this PR is to get ride of direct Kubernetes dependency. Expectation is being used in JobController to tell the number of pods/services they expect. 

In the future, Instead of `import k8s.io/kubernetes/pkg/controller`,  User need to `import github.com/kubeflow/common/pkg/controller.v1/expectation` and use `expectation.NewControllerExpectations` instead.

Signed-off-by: Jiaxin Shan <seedjeffwan@gmail.com>

/cc @gaocegege @terrytangyuan

### CODE REVIEW

**Comment by Jeffwan** [comment]
```
pkg/controller.v1/expectation/expectation_test.go:87:19: Error return value of `e.SetExpectations` is not checked (errcheck)
638	e.SetExpectations(rcKey, adds, dels)
639	                 ^
640pkg/controller.v1/expectation/expectation_test.go:123:19: Error return value of `e.SetExpectations` is not checked (errcheck)
641	e.SetExpectations(rcKey, 1, 2)
642	                 ^
643The command "golangci-lint run ./..." exited with 1.
```

This is too restrict.. it's pretty common to ignore output check. Disable `errcheck` for this.

**Comment by Jeffwan** [comment]
/hold

Please help on review first. I will run some real test against this version manually.

**Comment by Jeffwan** [comment]
@gaocegege This one bring expectation back to repo. We remove all the direct dependency of Kubernetes now.

**Comment by terrytangyuan** [comment]
Is this still on hold?

**Comment by Jeffwan** [comment]
/hold cancel

This can be merged.  @gaocegege

**Pull request merged**
