### PR TITLE
update volcano crd api to v1.16

### PR DESCRIPTION
**Pull request by Thor-wl**
Signed-off-by: Thor-wl <13164644535@163.com>

### CODE REVIEW

**Comment by Jeffwan** [comment]
```
# volcano.sh/apis/pkg/apis/scheduling

../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/scheduling/register.go:38:3: cannot use &PodGroup literal (type *PodGroup) as type runtime.Object in argument to scheme.AddKnownTypes:

	*PodGroup does not implement runtime.Object (missing DeepCopyObject method)

../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/scheduling/register.go:39:3: cannot use &PodGroupList literal (type *PodGroupList) as type runtime.Object in argument to scheme.AddKnownTypes:

	*PodGroupList does not implement runtime.Object (missing DeepCopyObject method)

../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/scheduling/register.go:40:3: cannot use &Queue literal (type *Queue) as type runtime.Object in argument to scheme.AddKnownTypes:

	*Queue does not implement runtime.Object (missing DeepCopyObject method)

../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/scheduling/register.go:41:3: cannot use &QueueList literal (type *QueueList) as type runtime.Object in argument to scheme.AddKnownTypes:

	*QueueList does not implement runtime.Object (missing DeepCopyObject method)

# volcano.sh/apis/pkg/apis/bus/v1alpha1

../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/bus/v1alpha1/register.go:46:3: cannot use &Command literal (type *Command) as type runtime.Object in argument to scheme.AddKnownTypes:

	*Command does not implement runtime.Object (missing DeepCopyObject method)

../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/bus/v1alpha1/register.go:47:3: cannot use &CommandList literal (type *CommandList) as type runtime.Object in argument to scheme.AddKnownTypes:

	*CommandList does not implement runtime.Object (missing DeepCopyObject method)
```

go build failed. Can you help fix it?

**Comment by Thor-wl** [comment]
> ```
> # volcano.sh/apis/pkg/apis/scheduling
> 
> ../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/scheduling/register.go:38:3: cannot use &PodGroup literal (type *PodGroup) as type runtime.Object in argument to scheme.AddKnownTypes:
> 
> 	*PodGroup does not implement runtime.Object (missing DeepCopyObject method)
> 
> ../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/scheduling/register.go:39:3: cannot use &PodGroupList literal (type *PodGroupList) as type runtime.Object in argument to scheme.AddKnownTypes:
> 
> 	*PodGroupList does not implement runtime.Object (missing DeepCopyObject method)
> 
> ../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/scheduling/register.go:40:3: cannot use &Queue literal (type *Queue) as type runtime.Object in argument to scheme.AddKnownTypes:
> 
> 	*Queue does not implement runtime.Object (missing DeepCopyObject method)
> 
> ../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/scheduling/register.go:41:3: cannot use &QueueList literal (type *QueueList) as type runtime.Object in argument to scheme.AddKnownTypes:
> 
> 	*QueueList does not implement runtime.Object (missing DeepCopyObject method)
> 
> # volcano.sh/apis/pkg/apis/bus/v1alpha1
> 
> ../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/bus/v1alpha1/register.go:46:3: cannot use &Command literal (type *Command) as type runtime.Object in argument to scheme.AddKnownTypes:
> 
> 	*Command does not implement runtime.Object (missing DeepCopyObject method)
> 
> ../../../../pkg/mod/volcano.sh/apis@v1.16.15/pkg/apis/bus/v1alpha1/register.go:47:3: cannot use &CommandList literal (type *CommandList) as type runtime.Object in argument to scheme.AddKnownTypes:
> 
> 	*CommandList does not implement runtime.Object (missing DeepCopyObject method)
> ```
> 
> go build failed. Can you help fix it?

Yes, i'm fixing it.

**Comment by Thor-wl** [comment]
@gaocegege @Jeffwan Can you help for rerun the CI ? The root reason is some bugs in the volcano.sh/apis and i've fixed it.

**Comment by Thor-wl** [comment]
It seems that the CI machine didn't `go get` the latest code of volcano.sh/apis v1.16.15 and still used cache. Becase the CI failed log shows that my error line is 39,  and it doesn't match the latest code. I'll try to submit a new PR and trigger the CI again.

**Comment by shinytang6** [comment]
> It seems that the CI machine didn't `go get` the latest code of volcano.sh/apis v1.16.15 and still used cache. Becase the CI failed log shows that my error line is 39, and it doesn't match the latest code. I'll try to submit a new PR and trigger the CI again.

maybe you need to run `go mod tidy` again?

**Comment by Thor-wl** [comment]
> > It seems that the CI machine didn't `go get` the latest code of volcano.sh/apis v1.16.15 and still used cache. Becase the CI failed log shows that my error line is 39, and it doesn't match the latest code. I'll try to submit a new PR and trigger the CI again.
> 
> maybe you need to run `go mod tidy` again?

Let me have a try,

**Pull request closed without merging**
