### PR TITLE
Fix dependency configuration

### PR DESCRIPTION
**Pull request by MartinForReal**
Remove unnecessary replace statements 
Add test dependencies.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Is there a way to check/validate this in the CI, e.g. similar to `go mod tidy`?

**Comment by gaocegege** [comment]
@terrytangyuan Yeah I think so.

**Comment by MartinForReal** [comment]
this kind of validation utility is still under discussion. ref: https://github.com/golang/go/issues/27005
A possible workaround is as described here: https://blog.urth.org/2019/08/13/testing-go-mod-tidiness-in-ci/

``` bash
#!/bin/bash
set -e
go mod tidy
STATUS=$( git status --porcelain go.mod go.sum )
if [ ! -z "$STATUS" ]; then
    echo "Running go mod tidy modified go.mod and/or go.sum"
    exit 1
fi
exit 0
```

**Comment by terrytangyuan** [comment]
Would you like to add it to part of the CI as well in this PR?

**Review by terrytangyuan — APPROVED** [review]
/approve

**Comment by terrytangyuan** [comment]
Build failed: https://travis-ci.com/github/kubeflow/common/builds/227049950

**Comment by gaocegege** [comment]
Ref https://travis-ci.com/github/kubeflow/common/builds/227050579#L332

**Comment by gaocegege** [comment]
Can you please update go mod?

Or is it caused by the go version?

**Pull request merged**
