### PR TITLE
CleanPodPolicyRunning cleans Pending phase pod

### PR DESCRIPTION
**Pull request by mkkb473**
#104

### CODE REVIEW

**Comment by ChanYiLin** [comment]
/lgtm
Thanks for your contribution !

**Review by gaocegege — COMMENTED** [review]
/lgtm

/assign @Jeffwan @johnugeorge @andreyvelich

**Comment by ChanYiLin** [comment]
just some wording issue in the comment

//Note that pending pod will ~~turn to be~~ turn into (or turn) running once schedulable,
// not cleaning it may leave ~~there~~ orphan running pod"s" in the ~~fure~~ future,
// we should ~~treet~~  treat it equivalent to running phase here.

**Comment by Jeffwan** [comment]
Nice catch. This would be helpful in some cases. 

/lgtm
/approve

**Pull request merged**
