### PR TITLE
Rollback #172 as it introduce hard requirements for the list values to not be empty

### PR DESCRIPTION
**Pull request by pugangxa**
Due to #175, rollback the changes of listtype.

### CODE REVIEW

**Comment by zw0610** [comment]
Would you mind check if this pr can fix issue #175 ?

**Comment by pugangxa** [comment]
> Would you mind check if this pr can fix issue #175 ?

Oops, will take a look.

**Comment by pugangxa** [comment]
Rollback this change due to #175. Tried and it works now.
@zw0610 @gaocegege

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
